### ISSUE TITLE
Pesquisas sobre as tecnologias

### ISSUE THREAD

**Issue by klyssmannoliveira** [fga-eps-mds/2021-1-hospitalar#10]
# Tarefa

Após a definição das tecnologias e ferramentas que serão utilizados no projeto, elaborar:

- [x] Bibliografia sobre as ferramentas;
- [x] Tutorial de ambientação (instalar, configurar e etc);
- [x] Tutorial básico de utilização

Divisão das tecnologias: 

- [x]  MongoDB: @PedroCassianoMartins 
- [x]  Django: @jvsdurso
- [x]  React: @pedrohelias
- [x]  Docker: @EduardoGurgel 

# Critério de aceitação
Apresentar um documento resumindo as tarefas;

**Comment by pedrohelias** [comment]
https://youtu.be/tbLziJchz48
Esse vídeo é bastante interessante, dá uma boa visão da utilização do React

**Comment by EduardoGurgel** [comment]
# Django

## 1. Passos iniciais Windows

### Instala o Python
   
    https://www.python.org/downloads/ 
    

### Executa o powershell como administrador
### Cria a pasta
     
    mkdir projetodjango
    
    cd projetodjango

### Instala o virtualenv
    
    pip install virtualenv

### Verifica a versão do virtualenv:
    
    virtualenv –-version

### Cria a máquina virtual
   
    python -m venv venv

### Entra na pasta virtual
   
    venv/Scripts/Activate

### Instala o Django
   
    pip install django

### Inicia o projeto Django
   
    Django-admin startproject nomedoprojeto

### Entra na pasta do projeto
 
    cd nomedoprojeto

### Inicia a aplicação
   
    python manage.py startapp aplicativo1

### Inicia o servidor
  
    python manage.py runserver

**Comment by PedroCassianoMartins** [comment]
# Tutorial de Ambientação MongoDB

Um documento que ensina como instalar e se ambientar no MongoDB

### Instale o MongoDB
	 https://www.mongodb.com/try/download/community
Baixe uma versão boa para o seu OS
Escolha o local que quiser para a instalação

### Instale MongoCompass
	 https://www.mongodb.com/try/download/compass
Baixe a última versão
Instale o mongoCompass

### Conectando o server

* Para usar o Mongo Compass precisamos primeiro habilitar o server do MongoDB
* Abra seu terminal e mude a pasta para a pasta de instalacao do MongoDB
* Execute o mongod.exe pelo terminal
* Abra outro terminal e muda também para a pasta do MongoDB
* Execute o mongos.exe pelo terminal

**Comment by jvsdurso** [comment]
## 2. Comandos básicos de Python

Como referência utilizar-se-á o documento disponível no link: [https://docs.python.org/pt-br/3/tutorial/](url)

### Leitura do teclado
```
...print("Digite seu nome:")
...nome = input()
>>> Time A
...print("Bem-vindo, ", nome)

...Bem vindo, Time A
```
### Condições
##### 

- IFs

Ex.:
``` 
>>> x = int(input("Leia um inteiro: ")) 
Leia um inteiro: 42
>>> if x < 0:
...     x = 0
...     print('Negativo se torna zero')
... elif x == 0:
...     print('Zero')
... elif x == 1:
...     print('Um')
... else:
...     print('Mais') 

... Mais
```

- For
```
for variavel in lista
comandos
```
Ex.: 
```
... nomes = ['Pedro', 'João', 'Leticia']
... for n in nomes:
...     print(n)

... Pedro
... João
... Leticia
```
### Classes
```
class ClassName:
    <statement-1>
    .
    .
    .
    <statement-N>
```
##### 

- Objetos de classe
```
class MyClass:
    """A simple example class"""
    i = 12345

    def f(self):
        return 'hello world'
```
Para instanciar uma classe usa-se:
```
x = MyClass()
```




> # Django
> ## 1. Passos iniciais Windows
> ### Instala o Python
> ```
> https://www.python.org/downloads/ 
> ```
> 
> ### Executa o powershell como administrador
> ### Cria a pasta
> ```
> mkdir projetodjango
> 
> cd projetodjango
> ```
> 
> ### Instala o virtualenv
> ```
> pip install virtualenv
> ```
> 
> ### Verifica a versão do virtualenv:
> ```
> virtualenv –-version
> ```
> 
> ### Cria a máquina virtual
> ```
> python -m venv venv
> ```
> 
> ### Entra na pasta virtual
> ```
> venv/Scripts/Activate
> ```
> 
> ### Instala o Django
> ```
> pip install django
> ```
> 
> ### Inicia o projeto Django
> ```
> Django-admin startproject nomedoprojeto
> ```
> 
> ### Entra na pasta do projeto
> ```
> cd nomedoprojeto
> ```
> 
> ### Inicia a aplicação
> ```
> python manage.py startapp aplicativo1
> ```
> 
> ### Inicia o servidor
> ```
> python manage.py runserver
> ```

**Comment by victordscabral** [comment]
Pesquisas sobre as tecnologias concluída, commits com documentos gerados. Issue finalizada.
