### ISSUE TITLE
Elaboração do TAP

### ISSUE THREAD

**Issue by klyssmannoliveira** [fga-eps-mds/2021-1-hospitalar#11]
# Tarefas
- [x] Verificar documentação disponibilizada pelo cliente;

> Com base no trabalho realizado no levantamento de referências sobre o TAP, fazer:

- [x] Termo de Abertura do Projeto;

# Critérios de aceitação
Documento modelo do TAP;

**Comment by SwampTG** [comment]
### Resumo dos Documentos (visto até agora)
## Padrões de Acreditação da Saúde Assistencial Militar 
>(visto até agora)

1. A Acreditação é o processo por meio do qual uma equipe experiente e
multidisciplinar de avaliadores, devidamente capacitada e sem vínculo
com a OMS avaliada, realiza a avaliação da organização

2. garantir a segurança de pacientes e colaboradores e a qualidade do
atendimento assistencial.

3. O processo de Acreditação compreende três tipos de avalição: de
Diagnóstico, de Acompanhamento e de Acreditação.

4. Avaliação de Diagnóstico tem caráter educativo e diagnóstico nos pro-
cessos de melhoria contínua da saúde assistencial militar nas OMS. Busca
reforçar a cultura de Segurança do Paciente, identificar os pontos fortes e
as oportunidades de melhoria, promover a cooperação interna entre as
pessoas e entre os processos, e complementar a capacitação dos novos
avaliadores.

5. Avaliação de Acompanhamento verifica como as OMS desenvolvem a
saúde assistencial militar com base nos relatórios de avaliação anteriores.
Tem por objetivo identificar os pontos fortes e as oportunidades de melho-
ria, complementar a capacitação dos novos avaliadores, atualizar a gover-
nança de saúde e sincronizar os esforços de minimização das não-confor-
midades.

6. Avaliação de Acreditação verifica o nível de compliance da OMS com os
padrões definidos para a acreditação da saúde assistencial no Exército,
atribuindo uma certificação correspondente.

7. Boas práticas são os conjuntos de procedimentos experimentados em
instituições de saúde e recomendados por órgãos de referência como a
Organização Mundial de Saúde (WHO), o Ministério da Saúde, a ANVISA
ou a Diretoria de Saúde.

8. A base da Acreditação, conforme mostra a figura, é a Segurança do
Paciente e Garantia da Qualidade que somente será atingida com o 
cumprimento dos protocolos

9. Parâmetros de Avaliação foram desenvolvidos com base no Manual
Brasileiro de Acreditação

## 10. Parâmetros:
    ##  Gestão Organizacional: Identifica o modelo de gestão adotado. Condução e Liderança.
        # Liderança:
            Descrição :Participação das Chefias; Controle e Planejamento; Políticas de Gestão; Comunicação.
            Itens na Planilha

        # Gestão de Qualidade e Segurança do Paciente:
            Descrição: Desenvolve modelo de gestão e estabelece mecanismos de execução e cumprimento. Padronizações. Padronização de documentação. Protocolos, procedimentos, sistematicas. 
            Itens na Planilha

       # Gestão de Pessoas:
            Descrição: Organização de pessoas, funções, seleção de pessoal, gerência de pessoas, capacitação,
            Itens na Planilha

        # Gestão do Cuidado ao Paciente:
            Descrição: Critérios de admissão, transferência, alta, acesso
            Itens na Planilha

        # Gestão Logística:
            Descrição: Processos sobre materiais, insumos e serviços. Gerenciamento de espaços e equipamentos. Controle de fornecedores. Manutenção. 
            Itens na Planilha
        
        # Gestão Logística:
            Descrição: Planejamento, organização e avaliação da performance. Controle de recursos. Uso racional. Uso de Informações. Custos.
            Itens na Planilha

        # Gestão da Comunicação
            Descrição: Comunicação interna e externa. Informações acessíveis. Comunicação social. Canais
            Itens na Planilha

    ## 2. Segurança do Paciente: Redução do risco desnecessário ao paciente.
        # Núcleo de Segurança do Paciente:
            Descrição: Garantir bom Funcionamento do núcleo. Ações, medidas e programas do NSP. Capacitação. Monitoramento e Avaliação de dados do sobre risco e incidentes.
            Itens na Planilha

        # Plano de Segurança do Paciente
            Descrição: Documentos de estratégias protocolos e procedimento referentes a: Medidas para cumprir os planos. Identificação dos pacientes. Segurança de insumos, Cirurgias Sign in, Sign out e time out. Higienização. Risco de queda e lesão. 
            Itens na Planilha
        
        # Vigilância de eventos adverso
            Descrição: Cultura de investigação. Organização de infos. Notificação de incidentes e óbitos. Prazos. Ações da NSP.
            Itens na Planilha

        # Prevenção e Controle de Infecções e Biossegurança
            Descrição: Riscos de infecção. Proteção dos pacientes e colaboradores. Garantir o Serviço de Controle de Infecção. Treinamento. Prevenção e Controle. Higienização. 
            Vigilância. Planos de contingência. SCI assessora planos e áreas. 
            Itens na Planilha

        # Controle da Informação do Paciente
            Descrição: Segurança dos dados e informações. Disponibilidade. Armazenamento e descarte.
            Itens na Planilha

    ## 3. Atenção ao Paciente: Cuidado dos pacientes. Interrelações. De acordo com complexidade e especialização do Hospital. Multidisciplinariedade. Acessibilidade e Continuidade. Plano de Seguimento do Cuidado ao Paciente. 

        # Gestão de Acesso  
            Descrição: recepção, acolhimento, admissão, transferência, orientação e alta. Agilidade de identificação e atendimento. Relações com redes de referência (quando não é possível no próprio hospital). Encaminhamento. Orientação
            Itens na Planilha.

        # Internação
            Descrição: Processos de assistência com permanência. Procedimentos para casos diferentes. Seguir segurança e controle de infecção. Equipe multidisciplinar.

        # Atendimento ambulatorial
            Descrição: Atendimento Eletivo. Assistência externa. Prevenção, diagnóstico, terapia e reabilitação. Agendamento.  

>  Observações sobre o relatório: 
1. Exibir gráfico das pontuações por tópicos, no relatório;
2. Definir níveis das notas para cada âmbito(Gestão Organizacional, Segurança do Paciente....), definido qual basta mencionar os resultados, em qual listar os resultados bons e diferenciar dos ruins das subcessões.
    Exs: 
        1) Gestão Organizacional: a OMS apresenta um nível muito bom de conformidade.
        2) Segurança do Paciente: ainda não ocorre de forma efetiva na OMS.
        3) Atenção ao Paciente: a OMS apresentou resultados regulares em cinco das nove
        seções avaliadas.
        4) Diagnóstico e Terapêutica: apresenta um nível muito bom de conformidade.
3. Gerar Anexos com comentário de cada item Parcialmente Conforme e Não conforme, de cada subcessão. Evidenciar quais itens não se aplicam (NA. Ex: Hospital que não realiza partos a parte de Neonatal não se apĺica). Estrutura do comentário: Comentado [P1]: Descrição do item, tal como está no Caderno de Padrões. Comentado [P2]: Status de conformidade atribuído pelo avaliador. Comentado [P3]: Comentário do avaliador.
4. Apresentação de Dados do Hospital e dos Avaliadores
5. Gerar resumo da Avaliação e de Resultados Globais.

> Observações sobre a Lista de Itens:
1. È possível converter em um DataFrame

**Comment by SwampTG** [comment]
Amálgama das planilhas utilizadas atualmente pelo cliente:
https://docs.google.com/spreadsheets/d/1cMCsFCTnPVCMMO_9eNXhoqwZymy3_DqoocLWNLfU4bU/edit#gid=58922840

**Comment by klyssmannoliveira** [comment]
Doc online para elaboração do TAP: https://docs.google.com/document/d/14165OkpRlasknB2Mk0SCVEU5QFaFeeMsa_ft6hCqt-Y/edit?usp=sharing

**Comment by klyssmannoliveira** [comment]
Tarefa concluída, modelo pronto!
