### ISSUE TITLE
Elaborar Business Canvas - Geral

### ISSUE THREAD

**Issue by SwampTG** [fga-eps-mds/2021-1-hospitalar#111]
# Descrição:

Criação e finalização do Business Canvas para entrega na R1. Importante para definição do projeto observando regras de negócio e oportunidades

# Tarefas:

- [x] Escolha do Template
- [x] Preenchimento do Canvas

# Critério de aceitação:

- [x] Canvas Suficiente para apresentação e R1

**Comment by victordscabral** [comment]
Documento de Canvas feito. Commit gerado. Issue finalizada.
