### ISSUE TITLE
Atualizar o README

### ISSUE THREAD

**Issue by augustocrmg** [fga-eps-mds/2021-1-hospitalar#115]
# Descrição:
Melhorar o README visando a avaliação R1 que ocorrerá na quinta-feira(16/09)

# Tarefas:

- [x] Utilizar linguagem mais formal e português correto
- [x] Links funcionais
- [x] Tópico 'status do projeto'
- [x] Tópico 'sobre o projeto'
- [x] Tópico 'tecnologias utilizadas'
- [x] Tópico 'como utilizar'
- [x] Tópico 'documentação'
- [x] Tópico 'Licenças

# Critério de aceitação:

- [x] Informações concisas 
- [x] README correto, funcional e bonito

**Comment by SwampTG** [comment]
README alterado na main. Sem necessidade de Merge. Documento suficiente para a R1.
