### ISSUE TITLE
Configuração do Git

### ISSUE THREAD

**Issue by klyssmannoliveira** [fga-eps-mds/2021-1-hospitalar#12]
# Tarefas
Com base nas referências levantadas na atividade de levantamento referencial, fazer:
- [x] Tutorial de configuração do ambiente Git em uma máquina;
- [x] Levantamento de referencias sobre o GitPages;
- [x] Documento com os comandos do Git;

# Critérios de aceitação
Certificar que todos os membros do grupo configurou o git no computador;

**Comment by PedroCassianoMartins** [comment]
Tutorial de Ambientação Git na sua máquina: 
docx:
[Ambientação Git.docx](https://github.com/fga-eps-mds/2021-1-hospitalar/files/6904510/Ambientacao.Git.docx)

pdf:
[Ambientação Git.pdf](https://github.com/fga-eps-mds/2021-1-hospitalar/files/6904511/Ambientacao.Git.pdf)

txt:
[Ambientação Git.txt](https://github.com/fga-eps-mds/2021-1-hospitalar/files/6904512/Ambientacao.Git.txt)

**Comment by PedroCassianoMartins** [comment]
Foto Exemplo de controle de arquivo: 
![photo_2021-07-26_18-44-29](https://user-images.githubusercontent.com/87657942/127587138-896dd17d-6bf4-437a-9ac9-0d096bc201f7.jpg)

**Comment by PedroCassianoMartins** [comment]
Link para os comandos do console GitBash: https://comandosgit.github.io/
Alguns desses comandos você pode utilizar da sua interface gráfica, como a clonagem e a alteração

**Comment by PedroCassianoMartins** [comment]
Como criar um GitHub Pages:
[Criando um GitHub Page.pdf](https://github.com/fga-eps-mds/2021-1-hospitalar/files/6934253/Criando.um.GitHub.Page.pdf)

site tutorial: https://pages.github.com/

**Comment by klyssmannoliveira** [comment]
Tarefa concluída, tutorial e bibliografias levantadas!
