### ISSUE TITLE
Revisão geral para a Release 1 - Geral

### ISSUE THREAD

**Issue by victordscabral** [fga-eps-mds/2021-1-hospitalar#124]
# Descrição:

Essa issue tem como tem como objetivo realizar uma revisão geral para a Release 1, ajustando, padronizando e corrigindo possíveis erros nos arquivos do repositório e git pages do projeto.  

# Tarefas:

- [x] Revisar o repositório
- [x] Revisar o Git Pages

# Critério de aceitação:

- [x] Repositório revisado 
- [x] Git Pages revisado

**Comment by SwampTG** [comment]
Documentos de corretude suficiente para  R1.  Cada documento foi averiguado e alterado. Não foram gerados novos documentos.
