### ISSUE TITLE
Levantamento de bibliografias sobre EAP e RoadMap

### ISSUE THREAD

**Issue by klyssmannoliveira** [fga-eps-mds/2021-1-hospitalar#13]
# Tarefas

- [x] Pesquisar trabalhos e referências sobre uma boa elaboração de uma EAP;
- [x] Pesquisar trabalhos e referências sobre uma boa elaboração de uma RoadMap;

# Critérios de aceitação
Modelo dos documentos (pronto para preencher)

**Comment by victordscabral** [comment]
### Referências da EAP de outros projetos:

**Referências utilizadas para o Protótipo 1:**

Principal referência:

- https://github.com/fga-eps-mds/2018.2-Lino/blob/master/docs/eap.md

Referências secundárias:

- https://github.com/fga-eps-mds/2018.2-Kalkuli/blob/master/docs/EstruturaAnalitica.md
- https://github.com/fga-eps-mds/2019.2-ArBC/blob/develop/docs/EAP.md


**Referências utilizadas para o Protótipo 2:**

Principal referência:

- https://github.com/fga-eps-mds/2016.2-SAS_FGA/wiki/EAP

Referência secundária:

- https://github.com/fga-eps-mds/2017.1-Escola-X/wiki/EAP

**Comment by victordscabral** [comment]
### Protótipo 1 da EAP para preenchimento:

- ![EAP - Hospitalar - Protótipo 1](https://user-images.githubusercontent.com/87657291/127969149-ab6bf6c2-0ac3-45fc-aa1f-af9a78c046b0.png)
- [EAP - Hospitalar - Protótipo 1.zip](https://github.com/fga-eps-mds/2021-1-hospitalar/files/6921564/EAP.-.Hospitalar.-.Prototipo.1.zip)

### Protótipo 2 da EAP para preenchimento:

- ![EAP - Hospitalar - Protótipo 2](https://user-images.githubusercontent.com/87657291/127969329-eae58eae-7d13-4461-8b54-54cb7ffa5732.png)
- [EAP - Hospitalar - Protótipo 2.zip](https://github.com/fga-eps-mds/2021-1-hospitalar/files/6921573/EAP.-.Hospitalar.-.Prototipo.2.zip)

**Site utilizado:**

- https://app.diagrams.net/

**Comment by victordscabral** [comment]
### Referências do RoadMap de outros projetos:

Principal referência:

- https://github.com/fga-eps-mds/2018.1-Lacos-da-Alegria/blob/develop/docs/roadmap.md

Referências secundárias:

- https://github.com/fga-eps-mds/2018.2-Lino/blob/master/docs/roadmap.md
- https://github.com/fga-eps-mds/2018.1-TropicalHazards-BI/blob/development/docs/metodology/roadmaps/Roadmap.png

**Modelos do RoadMap:**

RoadMap do Projeto:

- [RoadMap_Do_Projeto.pptx](https://github.com/fga-eps-mds/2021-1-hospitalar/files/6922756/RoadMap_Do_Projeto.pptx)


RoadMap de Metodologia:

- [RoadMap_De_Metodologia.pptx](https://github.com/fga-eps-mds/2021-1-hospitalar/files/6922759/RoadMap_De_Metodologia.pptx)

**Comment by victordscabral** [comment]
**Modelos do RoadMap para preenchimento:**

RoadMap do Projeto:

- [RoadMap_Do_Projeto.pptx](https://github.com/fga-eps-mds/2021-1-hospitalar/files/6922756/RoadMap_Do_Projeto.pptx)


RoadMap de Metodologia:

- [RoadMap_De_Metodologia.pptx](https://github.com/fga-eps-mds/2021-1-hospitalar/files/6922759/RoadMap_De_Metodologia.pptx)

**Comment by klyssmannoliveira** [comment]
Tarefa concluída, modelos estão prontos!
