### ISSUE TITLE
Atualização do Diagrama de Classes Unificado - Geral

### ISSUE THREAD

**Issue by PedroCassianoMartins** [fga-eps-mds/2021-1-hospitalar#135]
# Descrição:

Atualização do diagrama de classes visando uma melhor visualização e entendimento do documento.

# Pré-requisitos:

- [x] #36 

# Tarefas:

- [x] Mudança visual no diagrama de classes
- [x] Revisão do documento do diagrama de classes

# Critério de aceitação:

- [x] Melhor entendimento do documento

**Comment by PedroCassianoMartins** [comment]
Fiz a atualização do diagrama de classes, se tiver mais alguma dica ou pendência, por favor avisar.
![Diagrama de Classes0 2](https://user-images.githubusercontent.com/87657942/133286248-53d0ee89-33d5-44e2-a13a-764e3515d1de.png)

**Comment by victordscabral** [comment]
Documento atualizado. Commit realizado. Issue finalizada.
