### ISSUE TITLE
Definição dos Escopos dos Grupos

### ISSUE THREAD

**Issue by SwampTG** [fga-eps-mds/2021-1-hospitalar#14]
# Descrição
Após detalhamento do produto (#11 #13)  e da arquitetura (#9 e #8)    , permitir que os times trabalhem mais separademente em partes específicas do projeto.

# Tarefas
- [x]  Separar as funcionalidades
- [x]  Os times devem escolher uma dentre as funcionalidades, a princípio:
            1. Tela de login 
            2. Menu Principal 
            3. Checklist - Avaliação 
            4. Análise gráfica e Relatório

# Critérios de aceitação
1. Cada grupo deve postar a sua função para o projeto;

**Comment by augustocrmg** [comment]
Grupo B - Armazenamento, organização e visualização de dados para o gestor;

**Comment by gpersijn** [comment]
Documento de levantamento de requisitos funcionais e não-funcionais: https://unbbr-my.sharepoint.com/:w:/g/personal/190046091_aluno_unb_br/EQjNq_YGI2FNm2JmHRTyBBUBwrLmalCbmsoz0MMdoxNlug?e=q94bP8

**Comment by klyssmannoliveira** [comment]
1. Tela de login - Time C 
            2. Menu Principal - Time C 
            3. Checklist - Avaliação - Time A 
            4. Análise gráfica e Relatório - Time B

**Comment by klyssmannoliveira** [comment]
Issue concluída
