### ISSUE TITLE
Reunião Geral - 15/09/2021

### ISSUE THREAD

**Issue by SwampTG** [fga-eps-mds/2021-1-hospitalar#140]
# Descrição:

Atualização do Projeto para todos os membros. Discussão das Issues para a Sprint e distribuição entre os times.

# Tarefas:

- Reforçar continuidade na produtividade - pelo menos 1 commit significativo por semana!!

### Revisar:

- [x] Apresentação
- [x] Reforço das Políticas
- [x] Utilização do Repositório
- [x] Organização das Pastas
- [x] Fluxo a partir de agora
- [x] Prioridades atuais
- [x] Comunicação nas issues
- [x] Merge somente com PR

**Comment by victordscabral** [comment]
Reunião realizada, mas nem todos estavam presentes. Issue finalizada.
