### ISSUE TITLE
Filtragem do Relatório - Time B

### ISSUE THREAD

**Issue by SwampTG** [fga-eps-mds/2021-1-hospitalar#143]
# Descrição:

Definir os tópicos e gráficos que serão utilizados na pré-visualização do relatório.

# Tarefas:

- [x] Separar os itens
- [x] Tópicos mais importantes
- [x] Resumo na Página (Pré visualização)
- [x]  Gráficos
- [x]  Estrutura básica para o protótipo

# Critério de aceitação:

- [x] Listagem com tópicos
- [x]  Base para o protótipo de alta fidelidade

**Comment by gpersijn** [comment]
Link de filtragem das informações do relatório da parte interior da tela.

https://docs.google.com/document/d/1oJt4yUllyME1KG9fBG9mOMtWptQkTkh8BefyR4-6rdU/edit?usp=sharing
