### ISSUE TITLE
Alinhar e decidir como será feito o Protótipo de Alta Fidelidade - Geral

### ISSUE THREAD

**Issue by victordscabral** [fga-eps-mds/2021-1-hospitalar#144]
# Descrição:

Essa issue tem como objetivo realizar uma rápida reunião ou conversa para definir como será elaborado o protótipo de alta fidelidade. Ela é essencial para que o protótipo siga um mesmo padrão de design entre os três time, além de utilizar uma mesma ferramenta para confecção do próprio.

# Pré-requisitos:

- [x] #16 
- [x] #98 

# Tarefas:

- [x] Realizar rápida reunião ou conversa entre os times quanto ao protótipo 
- [x] Definir ferramenta que será utilizada para confecção
- [x] Definir a melhor forma de divisão e elaboração do documento para as partes de cada time

# Critério de aceitação:

- [x] Reunião ou conversa realizada
- [x] Ferramenta para confecção definida
- [x] Forma de divisão e elaboração do documento entre os times definida

**Comment by SwampTG** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/FAMil-6102b43329eebb00109363fd/issues/fga-eps-mds/2021-1-hospitalar/144?planning-poker) with ZenHub @pedrohelias @Eduardo-RFarias @DanielViniciusAlves @klyssmannoliveira @jvsdurso @Pedro-V8 @PedroMoraes39

**Comment by victordscabral** [comment]
Pré-requisitos atendidos. Issue finalizada.
