### ISSUE TITLE
Melhoria do documento de Identidade Visual - Geral

### ISSUE THREAD

**Issue by victordscabral** [fga-eps-mds/2021-1-hospitalar#146]
# Descrição:

Essa issue tem como objetivo realizar uma segunda melhoria no documento de Identidade Visual, tendo como referencial bons documentos de identidade visual de semestres passados. Um melhor preenchimento do documento deve ser realizado, tanto com texto quanto com imagens.

# Pré-requisitos:

- [x] #77 
- [x] #98 

# Tarefas:

- [x] Aprimorar e incrementar documento de Identidade Visual

# Critério de aceitação:

- [x] Commit e merge do documento aprimorado

**Comment by SwampTG** [comment]
Talvez fosse bom se reunir com um representante de cada time para finalizar a identidade.

**Comment by victordscabral** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/FAMil-6102b43329eebb00109363fd/issues/fga-eps-mds/2021-1-hospitalar/146?planning-poker) with ZenHub @Eduardo-RFarias

**Comment by victordscabral** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/FAMil-6102b43329eebb00109363fd/issues/fga-eps-mds/2021-1-hospitalar/146?planning-poker) with ZenHub @gpersijn @klyssmannoliveira

**Comment by victordscabral** [comment]
Melhorias no documento realizadas. Commit e merge feito. Issue finalizada.
