### ISSUE TITLE
[H16] - Componente Gráfico das Sessões - Time B

### ISSUE THREAD

**Issue by SwampTG** [fga-eps-mds/2021-1-hospitalar#150]
# Descrição:

Adiconar gráfico na página, que poderá ser modificado através de dados do banco de dados. A modificação de acordo com os dados do banco de dados será completada em nova issue ([H16 - Atualizar Gráficos por pontuações])

# Tarefas:

- [x] Criar Componente de Gráfico
- [ ] Gráfico de Pizza
- [x] Gráfico de Barras
- [x] Controlar cores dos gráficos
- [x] Verificar se é possível  receber dados do banco de dados

# Critério de aceitação:

- [x] Gráfico o qual será possível substituir campos fixos por dados do banco de dados em issue futura

**Comment by SwampTG** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/FAMil-6102b43329eebb00109363fd/issues/fga-eps-mds/2021-1-hospitalar/150?planning-poker) with ZenHub @augustocrmg @castroricardo1 @DanielViniciusAlves @Eduardo-RFarias @gpersijn @magnluiz

**Comment by SwampTG** [comment]
@gpersijn @Eduardo-RFarias  @augustocrmg  O que acham de usar o Charts.js? [link](https://www.chartjs.org/docs/latest/samples/other-charts/pie.html) é o que eu mai achei tutoriais com Django. Podemos servir dados em formato json para a página e renderiza o gráfico nela. Vou tentar implementar algo parecido com isso : https://blog.logrocket.com/using-chart-js-react/

**Comment by Eduardo-RFarias** [comment]
Já que o nosso backend é python, também é interessante as libs de python, como pandas, matplotlib, e outras bibliotecas de data science.

**Comment by SwampTG** [comment]
> Já que o nosso backend é python, também é interessante as libs de python, como pandas, matplotlib, e outras bibliotecas de data science.

Verdade, principalmente se o Reportlab tiver alguma facilitação para os gráficos utilizando essas libs.

**Comment by SwampTG** [comment]
Gráficos gerados, tanto no back-end, quanto no front, Decidir qual o tipo de implementação iremos utilizar em próxima issue e alimentar com o banco de dados

**Comment by SwampTG** [comment]
Gráficos gerados, tanto no back-end, quanto no front, Decidir qual o tipo de implementação iremos utilizar em próxima issue e alimentar com o banco de dados. Não terá merge agora.
