### ISSUE TITLE
Criar protótipo de baixa fidelidade

### ISSUE THREAD

**Issue by klyssmannoliveira** [fga-eps-mds/2021-1-hospitalar#16]
# Descrição:

Protótipos primitivos para ideias para a estrutura do projeto e decisões de front-end. Realizar a elaboração do Protótipo de Baixa Fidelidade, unificando as partes atribuídas para cada time em um só documento.

# Tarefas:

- [x] Marcar reunião para compartilhar protótipos
- [x] Brainstorming de protótipos
- [x] Criar um protótipo de baixa fidelidade do produto

# Critérios de aceitação:

- [x] Esboço do protótipo

**Comment by PedroCassianoMartins** [comment]
# Imagem simples de uma ideia de como seria a tabela de checklist
![protótipo simples da tabela de checklist](https://user-images.githubusercontent.com/87657942/129919869-1dcbfdae-ba68-46d5-8de5-68d286695ecd.png)

**Comment by pedrohelias** [comment]
![UML](https://user-images.githubusercontent.com/30875663/129926912-c453d8e6-e624-473d-ba2e-4423e89b5cd6.jpg)
[UML.pdf](https://github.com/fga-eps-mds/2021-1-hospitalar/files/7008380/UML.pdf)
Segue modelo pensado para criação da tela de checklist juntamente da UML pensada para a mesma, a ser discutido e melhorada com o time. Acompanha o PDF caso a imagem não esteja em boa qualidade.

**Comment by gpersijn** [comment]
<h2> Imagem de baixa fidelidade correspondente à pagina do item 3 do Menu: </h2>

![image](https://user-images.githubusercontent.com/56366957/130359739-d18cc77d-96c1-4ffb-affd-1851be23aff8.png)


[prototipo-baixa-fidelidade-menu-item3.pdf](https://github.com/fga-eps-mds/2021-1-hospitalar/files/7027573/prototipo-baixa-fidelidade-menu-item3.pdf)

**Comment by klyssmannoliveira** [comment]
Por favor, coloquem em uma pasta por meio de uma branch no repositório

**Comment by EduardoGurgel** [comment]
# Editar Avaliação
![222](https://user-images.githubusercontent.com/51385738/130694550-a9f6e0ce-72db-4af2-b125-d5f708ccfc5e.PNG)
# Inserir Checklist
![555](https://user-images.githubusercontent.com/51385738/130694540-3c5cf19e-db8b-4a23-a2ef-5499bea33579.PNG)

[Protótipo de baixa fidelidade.pdf](https://github.com/fga-eps-mds/2021-1-hospitalar/files/7042293/Prototipo.de.baixa.fidelidade.pdf)

**Comment by SwampTG** [comment]
**Esboços realizados**. Inserir protótipos no repositório.
