### ISSUE TITLE
Refatoração do Diagrama de Classes - Geral

### ISSUE THREAD

**Issue by victordscabral** [fga-eps-mds/2021-1-hospitalar#160]
# Descrição:

Essa issue tem como objetivo realizar uma revisão no Diagrama de Classes, na qual verificamos uma necessidade de se atualizar.

# Pré-requisitos:

- [x] #36

# Tarefas:

- [x] Verificar possíveis atualizações no documento
- [x] Refatorar o documento de Diagrama de Classes

# Critério de aceitação:

- [x] Commit e merge do documento de Diagrama de Classes atualizado

**Comment by PedroCassianoMartins** [comment]
@augustocrmg quando puder, se tiver pronto, coloca aqui a imagem e o documento do diagrama pra fechar a issue

**Comment by PedroCassianoMartins** [comment]
[diagrama.md](https://github.com/fga-eps-mds/2021-1-hospitalar/files/7212511/diagrama.md)

**Comment by victordscabral** [comment]
Diagrama de classes rafa torado. Commit gerado. Issue finalizada.
