### ISSUE TITLE
Refatoração da Modelagem de Banco de Dados - Geral

### ISSUE THREAD

**Issue by victordscabral** [fga-eps-mds/2021-1-hospitalar#161]
# Descrição:

Essa issue tem como objetivo realizar uma revisão na Modelagem de Banco de Dados, na qual verificamos uma necessidade de se atualizar.

# Tarefas:

- [x] Verificar possíveis atualizações no documento
- [x] Refatorar o documento de Modelagem de Banco de Dados

# Critério de aceitação:

- [x] Commit e merge do documento de Modelagem de Banco de Dados atualizado

**Comment by EduardoGurgel** [comment]
### Teste Modelo
![1A2](https://user-images.githubusercontent.com/51385738/135116470-47931107-f7c6-4e1f-8101-9975acfa8ca7.PNG)
### Mongo Compass
![ABCC](https://user-images.githubusercontent.com/51385738/135116490-c4313a4c-013a-4b90-b331-30f482ecc0b0.PNG)

**Comment by victordscabral** [comment]
Tarefa realizada. Commits gerados. Issue finalizada
