### ISSUE TITLE
Sprint 8 - Reunião - Geral

### ISSUE THREAD

**Issue by SwampTG** [fga-eps-mds/2021-1-hospitalar#169]
# Descrição:

Reunião com todos os times

# Tarefas:

- [x] Verificar dificuldades dos times
- [x] Discutir Protótipos
- [x] Manter produtividade
- [x] Pelo menos 1 Commit por semana
- [x] Mostrar Id. Visual
- [x] Verificar Diagramas Novos
- [x] União do Banco de Dados

# Critério de aceitação:

- [x] Times alinhados
- [x] Gestão de Risco

**Comment by SwampTG** [comment]
Alguma telas do Time C foram redistribuídas. Identificamos que para o futuro o time ficaria sobrecarregado.

**Comment by gpersijn** [comment]
TELAS:

1 - Tela de Login (Time C)
2 - Tela do Menu (Time C)
3 - Tela da Opção 1 do Menu - Gerar Código (Time B)
4 - Tela da Opção 4 do Menu - Gerenciamento [adm] :
    4.1 - Gerenciamento dos Usuários (Time C) 
    4.2 - Gerenciamento do Checklist  (Time A)
    4.3 - Gerenciamento da Avaliação (Time C) 
5 - Tela da Opção 2 do Menu - Preencher Checklist (Time A)
6 - Tela da Opção 3 do Menu - Gerar Relatório (Time B)

**Comment by victordscabral** [comment]
Reunião geral foi realizada como previsto. Entretanto, alguns tópicos ainda precisam ser discutidos, sendo então alocados para a reunião geral da Sprint 9. São eles:

- Necessidade de Refatorar documentos?
- Reforçar padrão de código (refatorado)
- Propor novas issues
- Rever RoadMap

**Comment by victordscabral** [comment]
Tarefas realizadas. Não há necessidade de gerar commit. Issue finalizada.
