### ISSUE TITLE
Configuração - GitPages

### ISSUE THREAD

**Issue by klyssmannoliveira** [fga-eps-mds/2021-1-hospitalar#17]
# Tarefas
Elaborar o primeiro protótipo do gitPages

# Critérios de aceitação
- [x] Esqueleto da apresentação dos principais documentos do projeto

**Comment by Pedro-V8** [comment]
Segue o link referente ao GitHub Pages: https://fga-eps-mds.github.io/2021-1-hospitalar/

Observações Iniciais:
- Tema, fonte e tudo o que está na página é provisório, o procedimento inicial teve o objetivo de criar a branch da página.
- Nada foi decidido ainda quanto à estrutura da página, nos próximos dias serão feitos os estudos referentes à criação da mesma.
-Será de extrema importância manter contato entre PO´s e SM dado o fato de que iremos depender da documentação e dos processos da elaboração do software para elaborar a página.

Qualquer dúvida estou à disposição.

**Comment by victordscabral** [comment]
**Boas referências para se ler e analisar:**

Guia para MarkDown (fornecido pelo próprio GitHub):
- https://guides.github.com/features/mastering-markdown/

Documentos gerais para GitPages (fornecido pelo próprio GitHub):
- https://docs.github.com/en/pages

Obs.: Observar as abas na esquerda do site

Outros temas para layout básico de GitPages:
- https://pages.github.com/themes/

- https://github.com/pages-themes/architect
- https://pages-themes.github.io/architect/

Segunda versão do cayman (possui mais informações):
- https://github.com/pages-themes/cayman
- https://pages-themes.github.io/cayman/

**Comment by victordscabral** [comment]
Protótipo do Git Pages atualizado. Foram integrados os textos (parte visual do site) e códigos ("index.md" e "_config.yml") da primeira e segunda versões do tema padrão Cayman.

**Comment by victordscabral** [comment]
Tarefa concluída. Estrutura do GitPages feita, necessário atualizações constantes no layout e componentes.
