### ISSUE TITLE
Organizar treinamento de tecnologias

### ISSUE THREAD

**Issue by SwampTG** [fga-eps-mds/2021-1-hospitalar#18]
# Descrição
Se preparar para aplicar as tecnologias definidas na arquitetura.

# Tarefas
- [x] Treinamento de React (preferência utilizando TypeScript);
- [x] Treinamento de DjangoRest (Integração com React);
- [x] Treinamento de MongoDB (Com os model Django);
- [x] Modelo de CRUD com as tecnologias mencionadas;

# Critérios de Aceitação
Developers capazes de manipular o modelo base de CRUD criado e adicionar páginas;

**Comment by SwampTG** [comment]
Modelo inicial do -> [Crud base](https://github.com/Eduardo-RFarias/Django-React-test.git) criado por @Eduardo-RFarias

**Comment by Eduardo-RFarias** [comment]
O modelo foi atualizado e já está aqui nesse repositório na branch material-ui. O template já implementa todas as tarefas exceto o mongo db (no momento está com sqlite) mas estou trabalhando nisso.

**Comment by Eduardo-RFarias** [comment]
agora falta organizar e fazer o treinamento.

**Comment by Eduardo-RFarias** [comment]
Falta marcar a data.

**Comment by augustocrmg** [comment]
<h2>Primeiro treinamento</h2>

- <h3>dia 23/08</h3>
- <h3>Treinamento de caráter introdutório dos seguintes assuntos</h3>

      - React
      - Django 
      - MongoDb 
      - Padrões de projeto

- <h3>Seria bom que todos tivessem tentato assistir ao menos uma parte desse link :</h3>

      - https://www.youtube.com/watch?v=VBqJ0-imSMU&t=3244s
