### ISSUE TITLE
Reunião Sprint 10 - Time B

### ISSUE THREAD

**Issue by SwampTG** [fga-eps-mds/2021-1-hospitalar#204]
# Descrição:

Vamos discutir novas issues e débitos adicionados. Priorizar finalização das telas e implementação do Backend
através dos testes e templates que já foram feitos. Verificar responsividade das telas.

# Tarefas:

- [x] Novas Issues
- [x] Verificar issues abertas (dá para terminar hoje?)
- [x] Planning Poker
- [x] Prioridades
- [x] Priorizar pareamento
- [x] Respeitar Velocity (Não exceder 40 pontos)
- [x] Respeitar prazo da Sprint
- [x] Donos das issues
- [x] Review
- [x] Retrospectiva
- [x] Dificuldades
- [x] Riscos
- [x] Knowledge
- [x] HealthCheck

**Comment by gpersijn** [comment]
![Screenshot from 2021-10-05 22-11-50](https://user-images.githubusercontent.com/56366957/136125196-08cc5cd2-553a-4a85-af8d-206caafb47bd.png)
