### ISSUE TITLE
Abertura e Fechamento sprint 8 - Time C

### ISSUE THREAD

**Issue by PedroMoraes39** [fga-eps-mds/2021-1-hospitalar#244]
# Descrição:
Criar e finalizar os arquivos de abertura e fechamento da Sprint 8

# Tarefas:
- [x] Criar branch associada à issue
- [x] Criar pasta sprint 8 dentro de dos/sprints/Time_C
- [x] Criar arquivos abertura_sprint e fechamento_sprint
- [ ] Gerar os gráficos

# Critério de aceitação:
- [x] Branch com a Issue associada
- [x] Pastas e arquivos criados
- [x] Gráficos Gerados

**Comment by Pedro-V8** [comment]
Documentos gerados e inseridos na main
