### ISSUE TITLE
Estudos da Linguagem JavaScript - Time C

### ISSUE THREAD

**Issue by Pedro-V8** [fga-eps-mds/2021-1-hospitalar#25]
# Descrição:
Dado à decisão de implementar o Frontend em ReactJs, favor realizar estudos quanto aos tópicos fundamentais da Linguagem JavaScrit para se habituar ao ambiente de desenvolvimento do React.

# Tarefas:
- [x] Buscar ferramentas de aprendizagem
- [x] Estudar tecnologias indicadas
- [x] Treinamento das tecnologias aprendidas

# Critérios de Aceitação:
- [x] Links de artigos, vídeos, livros, cursos e etc.

**Comment by eng-Bruno** [comment]
Link do curso gratuito sobre JavaScript da Rocketseat:
https://app.rocketseat.com.br/node/o-guia-estelar-de-java-script/group/introducao-3/lesson/abertura-13
