### ISSUE TITLE
Organizar o ZenHub

### ISSUE THREAD

**Issue by augustocrmg** [fga-eps-mds/2021-1-hospitalar#26]
Como vocês podem verificar, o ZenHub já mostra as issues criadas, elas só precisam ser remanejadas. Seria bom que nós organizassemos possibilitando o uso da metodologia KanBan, acredito que seria bom para manter o trabalho organizado e em dia.

**Comment by PedroCassianoMartins** [comment]
Onde encontro esse ZenHub?

**Comment by augustocrmg** [comment]
@PedroCassianoMartins você entra nesse link aqui: https://www.zenhub.com/ , e conecta com o seu github, ai você já vai ter acesso ao zenhub do trabalho.

**Comment by klyssmannoliveira** [comment]
Issue, concluída. Não há necessidade de gerar documento.
