### ISSUE TITLE
Elaboração do Documento de Metodologia

### ISSUE THREAD

**Issue by victordscabral** [fga-eps-mds/2021-1-hospitalar#27]
#Tarefas:

Realizar elaboração do documento de Metodologia.

#Critério de aceitação:

- [x] Entrega da versão final ou parcial do documento de Metodologia.

**Comment by klyssmannoliveira** [comment]
Encontra-se no endereço: https://github.com/fga-eps-mds/2021-1-hospitalar/tree/gh-pages/projeto/Metodologia

**Comment by klyssmannoliveira** [comment]
Documento de Metodologia, finalizado. Tarefa concluída
