### ISSUE TITLE
Pesquisas: Docker

### ISSUE THREAD

**Issue by klyssmannoliveira** [fga-eps-mds/2021-1-hospitalar#3]
# Tarfeas
Referências para a utilização do docker durante o projeto.

# Critérios de aceitação

- [x] Links de referência para o aprendizado do Docker

**Comment by pedrohelias** [comment]
Links úteis:

https://blog.geekhunter.com.br/docker-na-pratica-como-construir-uma-aplicacao/

**Comment by pedrohelias** [comment]
https://youtu.be/np_vyd7QlXk

**Comment by pedrohelias** [comment]
https://youtu.be/97jWpWp4Pnc

**Comment by Pedro-V8** [comment]
Integração do Docker com NodeJs - Rocketseat

https://www.youtube.com/watch?v=AVNADGzXrrQ

**Comment by victordscabral** [comment]
Site com bom resumo sobre o docker:
[https://balta.io/blog/docker-instalacao-configuracao-e-primeiros-passos](url)
