### ISSUE TITLE
Estudo de MongoDB

### ISSUE THREAD

**Issue by PedroCassianoMartins** [fga-eps-mds/2021-1-hospitalar#30]
# Tarefas

-  Devido à decisão de implementar um banco de dados, realizaremos estudos quanto aos tópicos fundamentais do bando de dados NoSQL MongoDB para se habituar ao ambiente de desenvolvimento do MongoDB.

# Critérios de Aceitação:

- [x] Links de curso, videoaulas, documentos, etc.

**Comment by PedroCassianoMartins** [comment]
Arquivo com os comandos úteis do MongoDB:

[comandosMongoDB.md](https://github.com/fga-eps-mds/2021-1-hospitalar/files/7002970/comandosMongoDB.md)

**Comment by PedroCassianoMartins** [comment]
# Comandos MongoDB:

* **show dbs** = mostra toda a database

* **use (database)** = mostra uma específica

* **show collections** = lista a collections do canal database

* **db.createCollection("nome")** = cria uma collection

* **db.nomeCollection.insert({conteúdo})** = inseri um conteúdo na collection com o conteúdo dentro das chaves

* **db.nomeCollection.insertMany( [ { conteudo } ), ( {conteudo} ] )** = inseri varios conteúdos na collection com o conteudo dentro das chaves

* **db.collection.find()** = busca as coisas do collection digitado e da pra procurar com conteúdo dentro do collection como ("name: blabla") 

entre parênteses
*Ex: db.collection.find({"name: blabla"})*

* **db.collection.find().limit(n)** = busca com um limite

* **db.collection.find().count()** = retorna a quantidade de itens na collection. Também dá pra fazer um count com o conteúdo do find.
Ex: db.collection.find({"name: blabla"}).count()

* **db.collection.remove()** = remove o registro do item do id digitado dentro dos parênteses naquela collection
*Ex: db.collection.remove({_id: ObjectId(“12cd345325dfgsae213”)})*

* **db.collection.update()** = altera um item do registro na collection
*Ex: db.collection.upadte(
    {_id: ObjectId(“12cd345325dfgsae213”)},
    {$set: {name: “blehbleh”}}
) *

## +Comandos com find
Dá para encontrar registros com, por exemplo, preços menores e iguais, ou preços maiores e iguais a um certo número que deseje com:
* $eq = igual
* $gt = maior
* $gte = maior ou igual
* $lt = menor
* $lte = menor ou igual

*Ex: db.collection.find({price: { $eq: 30.0}})* = procura itens com preços iguais a 30

Também dá pra procurar itens que não tem aquele preço com:

* $ne = retorna itens que não tem aquele valor
* $nin = retorna itens que não tem aqueles valores

Existem também outras ajudas com find como:
* $and = procura itens com 2 ou mais valores
* $or = procura itens com 1 valor ou outro.

**Comment by PedroCassianoMartins** [comment]
(ComandosMongoDB)[comandosMongoDB.md](https://github.com/fga-eps-mds/2021-1-hospitalar/files/7003180/comandosMongoDB.md)

**Comment by PedroCassianoMartins** [comment]
[Comandos MongoDB.txt](https://github.com/fga-eps-mds/2021-1-hospitalar/files/7037002/Comandos.MongoDB.txt)

**Comment by PedroCassianoMartins** [comment]
Colocarei algumas referências para estudar o MongoDB (vídeos de youtube, cursos, etc.)

Curso para Iniciantes (Youtube):
https://www.youtube.com/watch?v=u3sVM3viDtQ&list=PLxuFqIk29JL0DMM0Z-S9_XEHAexXvhYyb&ab_channel=NatanielPaivaOficial

MongoDB em 15 min (Youtube):
https://www.youtube.com/watch?v=j-cjF1GkEMQ&ab_channel=CanalTI

MongoDB em 1h (Youtube):
https://www.youtube.com/watch?v=x9tC0eK0GtA&ab_channel=MatheusBattisti-HoradeCodar

Curso de MongoDB no DIO (Curso):
https://web.digitalinnovation.one/course/introducao-ao-mongodb-e-bancos-de-dados-nosql/learning/d8c1eb33-27f5-44f9-a57c-68d65fcac8da/?back=/browse

**Comment by victordscabral** [comment]
Estudo de MongoDB concluído, commit com documento gerado. Issue finalizada.
