### ISSUE TITLE
Políticas do Repositório

### ISSUE THREAD

**Issue by SwampTG** [fga-eps-mds/2021-1-hospitalar#33]
# Descrição
Política de branches e de commits, para padronização e fácil identificação das ações no repositório.

# Tarefas
- [x] Definir branches fixas
- [x] Padrão de Nomes das Branches
- [x] Padrão de Mensagens do Commit
- [x] Rotinas de comandos antes do merge
- [x] Padrão de PR

# Critérios de aceitação
- [x] Primeira versão do documento de Políticas do repositório.

**Comment by victordscabral** [comment]
Pastas com os documentos solicitados:
https://github.com/fga-eps-mds/2021-1-hospitalar/tree/main/docs/politicas

**Comment by victordscabral** [comment]
Documento de Políticas do Repositório finalizado. Tarefa concluída.
