### ISSUE TITLE
Atualizar template e descrição de Issues passadas e presentes

### ISSUE THREAD

**Issue by victordscabral** [fga-eps-mds/2021-1-hospitalar#34]
# Descrição:

Manter padrão de issues mais explicativas, com tarefas e pré-requisitos. Separar no máximo de tarefas possível. Sempre verificar se a issue pode ser desmebrada em mais issues.

# Tarefas:

- [x] Realizar atualização do template do documento [template_issues](https://github.com/fga-eps-mds/2021-1-hospitalar/blob/main/docs/template_issues/template_issues.md).
- [x] Atualizar descrição de Issues passadas e presentes para novo modelo.

# Critério de aceitação:

- [x] Atualização do template para nova versão.
- [x] Atualização da descrição de Issues passadas e presentes.

**Comment by SwampTG** [comment]
**Revisão de issues realizada e template modificado**
