### ISSUE TITLE
Pesquisas: Git

### ISSUE THREAD

**Issue by klyssmannoliveira** [fga-eps-mds/2021-1-hospitalar#4]
# Tarefas
Referências para a utilização do Git durante o projeto.

# Critérios de Aceitação

- [x] Referências de informações para o melhor aprendizado para a utilização do Git

**Comment by EduardoGurgel** [comment]
https://comandosgit.github.io/

**Comment by klyssmannoliveira** [comment]
Vídeos de Git e contribuição colaborativa: https://www.youtube.com/watch?v=hBu6fYH07nQ

**Comment by PedroCassianoMartins** [comment]
Documentação do git:
https://git-scm.com/doc
