### ISSUE TITLE
Elaboração do Diagrama de Classes - Time B

### ISSUE THREAD

**Issue by victordscabral** [fga-eps-mds/2021-1-hospitalar#46]
# Descrição:

Diagrama de classes, necessário para modelar o [Banco de Dados](#23) e traçar as bases do projeto. Realizar a elaboração do Diagrama de Classes referente ao Banco de Dados da parte atribuída ao Time B.

# Pré-requisitos:

- [x] #16 

# Tarefas:

-  [x] Diagrama de Classes do Relatório - Time B 

# Critério de aceitação:

- [x] Diagrama de Classes inicial : parte atribuída ao Time B

**Comment by Eduardo-RFarias** [comment]
Recomendo criar um documento compartilhado no docs, etc.
O diagrama pode ser do modelo que preferirem, a parte importante é o detalhamento dos objetos, atributos e métodos.
Nós precisamos saber qual vai ser a estrutura de cada dado e como trabalhar com ele.

**Comment by SwampTG** [comment]
Diagrama adicionado ao documento de arquitetura.
