### ISSUE TITLE
Modelagem da API do banco de dados - Time B

### ISSUE THREAD

**Issue by SwampTG** [fga-eps-mds/2021-1-hospitalar#59]
# Descrição:

Modelagem utilizando Diagramas de Banco de Dados e as Classes no Django. Utilizar os diagramas de classe.

# Pré-requisitos:

- [x] #46 

# Tarefas:

- [x] Criação das Classes básicas utilizando Django
- [x] Criação dos atributos das Classes
- [x] Comentar o código

# Critério de aceitação:

- [x]  Banco suficiente para proposta de solução (Release 1)

**Comment by Eduardo-RFarias** [comment]
Aprendemos a fazer e implementamos um dos diagramas para tester.

**Comment by SwampTG** [comment]
Essa issue pode ser fechada? Será dado merge?

**Comment by SwampTG** [comment]
Já que o Merge foi fechado, será feita em outra branch? @Eduardo-RFarias @augustocrmg  @DanielViniciusAlves

**Comment by SwampTG** [comment]
Models serão unidos com os do restante do projeto.
