### ISSUE TITLE
Organização de funções

### ISSUE THREAD

**Issue by augustocrmg** [fga-eps-mds/2021-1-hospitalar#6]
Organizar o cargo de cada pessoa do time, sendo eles:

- Product Owner
- Scrum Master
-  Dev Ops
- Arquiteto
- Tecnologia
- Tecnologia

# Critérios de aceitação

- [x]  Cada grupo deve informar a função dos membros e o contato

**Comment by SwampTG** [comment]
Guia do Scrum com os papéis, métodos e artefatos. [https://scrumguides.org/scrum-guide.html]

**Comment by klyssmannoliveira** [comment]
# Time A - Grupo 2
Scrum Master:Klyssmann (@klyssmannoliveira)
Product Owner Klyssmann (@klyssmannoliveira)
Dev Ops: Eduardo (61) 9 8123-6435
Arquiteto: Pedro(@pedrohelias)(984183063 wpp)
Tecnologia: Victor Cabral (61) 99101 - 7132
Tecnologia: Pedro Lucas (61) 99141 - 4645

**Comment by augustocrmg** [comment]
### Time B - Grupo 3
Scrum Master: Adrian Soares Lopes ()
Product Owner: Gustave Augusto Persijn ()
Dev Ops: Ricardo de Castro Loureiro ()
Arquiteto: Magno Luiz Vale Vieira ()
Tecnologia: Augusto Durães Camargo (@azrael3333 - Telegram)
Tecnologia: Eduardo Rodrigues de Faria ()
Tecnologia: Daniel Vinicius Ribeiro Alves ()

**Comment by Pedro-V8** [comment]
### Time C ###

- Scrum Master: Pedro Vieira (61 996869861-> Wpp)
- Product Owner: Pedro Moraes (61 986158829 -> Wpp)
- Dev Ops: Thiago Vivan ( 61 998257765 -> Wpp)
- Arquiteto: Gabriel Luiz (61 998701043 -> Wpp)
- Tecnologia: Igor Thiago (61 981921533 -> Wpp)
- Tecnologia: Bruno (61 984672415 -> Wpp)
