### ISSUE TITLE
União da Modelagem do Banco de Dados - Geral

### ISSUE THREAD

**Issue by SwampTG** [fga-eps-mds/2021-1-hospitalar#62]
# Descrição:

DevOps e Desenvolvedores devem se reunir para verificar e unificar a modelagem do banco de dados

# Pré-requisitos:

- [x] #69  
- [x] #59 
- [ ] #64 

# Tarefas:

- [ ] Marcar reunião antes do final da Sprint
- [ ] Reunir e discutir o modelo
- [ ] Definir o modelo

# Critério de aceitação:

- [ ] Modelo suficiente para a Release 1 e para iniciar o desenvolvimento

**Comment by EduardoGurgel** [comment]
### Modelo Time A
<img width="812" alt="1a" src="https://user-images.githubusercontent.com/51385738/132959780-efff3a9f-9fe3-4b6c-8efb-039f76d1225a.PNG">
<img width="548" alt="2a" src="https://user-images.githubusercontent.com/51385738/132959781-8b2919af-c648-441d-8998-a4068fbb428c.PNG">

**Comment by victordscabral** [comment]
Pessoal dos Times B e C. Preciso que realizem essa issue urgente, ela já está bem atrasada. Não sei se já fizeram as issues #59 e #64 referenciada nos pré-requisitos, mas peço que encarecidamente as façam logo.

**Comment by victordscabral** [comment]
@Pedro-V8 @PedroMoraes39. Para que essa issue seja executada, continuamos no aguardo da finalização da issue [Modelagem Banco de Dados - Time C](https://github.com/fga-eps-mds/2021-1-hospitalar/issues/64) por parte do Time C.

**Comment by victordscabral** [comment]
Issue fechada, mas com a parte do Time C ausente: [Modelagem Banco de Dados - Time C](https://github.com/fga-eps-mds/2021-1-hospitalar/issues/64).
