### ISSUE TITLE
Organizar reunião para separar Features - Geral

### ISSUE THREAD

**Issue by SwampTG** [fga-eps-mds/2021-1-hospitalar#68]
# Descrição:

Reunião que terá, ao menos, os POs e Developers de todos os times para separar o que será feito por cada time para a Release 1 (principalmente) e dentro do RoadMap.

# Tarefas:

- [x] Definir horário da Reunião
- [x] Realizar reunião

# Critério de aceitação:

- [x] Features separadas

**Comment by victordscabral** [comment]
Issue finalizada, features separadas. Sem necessidade de gerar documento.

**Comment by victordscabral** [comment]
Issue finalizada, features separadas. Sem necessidade de gerar documento.
