### ISSUE TITLE
Contato com o Cliente

### ISSUE THREAD

**Issue by SwampTG** [fga-eps-mds/2021-1-hospitalar#7]
# Descrição
Reunir (não só, mas principalmente) os PO's de todos os times com o cliente.

# Tarefas
- [x] Elaboração de pauta com os principais tópicos para entrevista com o cliente
- [x] Iniciar contato com o cliente
- [x] Marcar e realizar reunião com o cliente
- [x] Cumprir as perguntas: No doc (adicionem): [Perguntas relevantes](https://docs.google.com/document/d/1AgMX9CKyFwyX64Xt0r4MLAdFMtjhgU7ErD7KamQ0wDE/edit?usp=sharing)
- [x] Reunir requisitos do produto
- [x] Definir módulos do produto

# Critérios de aceitação
- [x] Feedback do cliente
- [x] Abrangência dos tópicos de Requisitos do documento de Escopo

**Comment by SwampTG** [comment]
Nome do cliente: PIVETTA
Contato: pasam.dgp@gmail.com
Postagens: https://www.facebook.com/page/118510713324246/search/?q=PASAM

**Comment by SwampTG** [comment]
Reunião marcada dia 08/10/2021 às 16:00 h

**Comment by victordscabral** [comment]
Tarefa concluída. Contato com o cliente realizado com sucesso. O cliente se propôs disponível para resposta de possíveis dúvidas em geral.
