### ISSUE TITLE
Revisão e continuação do Backlog - Time A

### ISSUE THREAD

**Issue by victordscabral** [fga-eps-mds/2021-1-hospitalar#71]
# Descrição:

Desenvolvedores devem continuar e revisar o documento de BackLog (#42). Atualizações necessárias, comentários e correções devem ser realizadas de acordo com as necessidades do projeto, levando em consideração a parte do projeto atribuída ao time A. 

# Pré-requisitos:

- [x] #19 

# Tarefas:

- [x] Revisão e correção do Documento
- [x] Verificar e atualizar Épicos
- [x] Adicionar novas informações, levando em consideração a parte do projeto atribuída ao time A

# Critério de aceitação:

- [x] Documento atualizado e suficiente para Release 1

**Comment by PedroCassianoMartins** [comment]
##Backlog revisado
Revisao do backlog feita pelo time A (Pedro Cassiano, João Durso e Eduardo Gurgel)
[backlog.md](https://github.com/fga-eps-mds/2021-1-hospitalar/files/7095157/backlog.md)

**Comment by victordscabral** [comment]
Issue finalizada, commits gerados e documento atualizado.
