### ISSUE TITLE
Dojo de MongoDB - Geral

### ISSUE THREAD

**Issue by victordscabral** [fga-eps-mds/2021-1-hospitalar#75]
# Descrição:

Realizar Dojo de treinamento para MongoDB (banco de dados). 

1. Esse dojo pode ser feito via reuniões, vídeos produzidos e/ou material de pesquisa, tendo como função capacitação de todos os times para utilização das tecnologias. 
 
3. Reforço que **todos os integrantes de todos os times** deverão assistir e estudar os materiais disponibilizados

# Tarefas:
- [x] Dojo de treinamento através de reuniões, vídeos e/ou materiais sobre o tema MongoDB 

# Critério de aceitação:

- [x] Realizações de dojo online e/ou entrega de vídeos e materiais sobre o tema

**Comment by Eduardo-RFarias** [comment]
Vou atualizar o treinamento para incluir comandos do mongo db, mas ainda preciso da data do treinamento.

**Comment by Eduardo-RFarias** [comment]
Foi mostrado como instalar o mongo db e é basicamente só isso que vamos fazer.
O resto será feito com a API e faz parte do treinamento de backend.

**Comment by victordscabral** [comment]
Materiais entregues. Issue finalizada.

**Comment by victordscabral** [comment]
Materiais entregues. Issue finalizada.
