### ISSUE TITLE
Dojo de JavaScript/React.js - Geral

### ISSUE THREAD

**Issue by victordscabral** [fga-eps-mds/2021-1-hospitalar#76]
# Descrição:

Realizar Dojo de treinamento para JavaScript/React.js (FrontEnd). 

1. Esse dojo pode ser feito via reuniões, vídeos produzidos e/ou material de pesquisa, tendo como função capacitação de todos os times para utilização das tecnologias. 
 
3. Reforço que **todos os integrantes de todos os times** deverão assistir e estudar os materiais disponibilizados

# Tarefas:
- [x] Dojo de treinamento através de reuniões, vídeos e/ou materiais sobre o tema JavaScript/React.js

# Critério de aceitação:

- [x] Realizações de dojo online e/ou entrega de vídeos e materiais sobre o tema

**Comment by Eduardo-RFarias** [comment]
Tenho um treinamento pronto sobre isso, só precisamos marcar o dia.

**Comment by Eduardo-RFarias** [comment]
Lembrar de ensinar o Material-ui e async await
