### ISSUE TITLE
Modelo de Identidade Visual - Geral

### ISSUE THREAD

**Issue by Pedro-V8** [fga-eps-mds/2021-1-hospitalar#77]
# Descrição:
Criar um modelo que descreva os padrões visuais que serão usados no projeto, tais como palheta de cores, padrões de formulários, fontes de texto e etc.

# Tarefas:

- [x] Determinar padrões de cores, texto, formulário
- [x] Criar uma branch para determinada Issue
- [x] Criar documento sobre a tarefa descrita

# Critério de aceitação:
- [x] Branch da Issue
- [x] Documento commitado com a marcação da Issue

**Comment by victordscabral** [comment]
Issue finalizada. Branch criado, commit gerado e primeria versão do documento iniciada.

**Comment by klyssmannoliveira** [comment]
Documento commitado com a marcação da Issue
