### ISSUE TITLE
Alinhamento das tecnologias

### ISSUE THREAD

**Issue by klyssmannoliveira** [fga-eps-mds/2021-1-hospitalar#8]
# Tarefas

- [x] Reunir os três times para a definição das tecnologias e ferramentas que serão utilizadas no projeto;

# Critérios de aceitação
Documento com as ferramentas definidas.

**Comment by pedrohelias** [comment]
https://youtu.be/JD-age0BPVo

**Comment by pedrohelias** [comment]
1ª ATA - Arquitetura de Software - Hospital
=================

   * [Procedência](#Procedência) 
   
     Reunião realizada a partir do Discord, iniciada pontualmente às 19h30 e finalizada às 20h04.
   * [Pauta da Reunião em tópicos](#Pauta-da-Reunião-em-tópicos)
      * [Front-End](#Front-End): html + css + javascript, React.
      * [Back-End](#Back-End): Python + Django ou Node.js.
      * [Banco de dados](#Banco-de-dados)
      * Verificar nível de proficiência das pessoas. 
      * Delimitar execução do documento de arquitetura
      
   * [Resoluções](#Resoluções)
   
  
    
      * [Front-End](#Front-End): Utilizar HTML + CSS + JavaScript(A tríade de desenvolvimento básico para desenvolvimento WEB quanto ao Front-End), e o framework React, uma biblioteca do JavaScript que facilita o desenvolvimento de aplicações Front-End.
      
      * [Back-End](#Back-End): Utilizar a linguagem Python por sua simplicidade e atual ascendência, fora a utilização em aplicações semelhantes ao tema solicitado, verificado em pesquisas a respeito dos projetos nos semestres anteriores. Quanto ao FrameWork, optou-se por utilizar: Django; ferramenta que facilita e dinamiza o desenvolvimento web, utilizando Python. Esta escolha ainda encontra-se em aberto pois há a opção de utilizar o framework Node.js, baseado em JavaScript. A seleção do framework a ser utilizado deve ser concluida após o retorno do cliente com especificações mais bem definidas sobre as necessidades do projeto, por se tratar de FrameWorks com vantagens e desvantagens diferentes. 

      * [Banco de dados](#Banco-de-dados): O mesmo problema relatado acima implica na escolha do banco de dados, desde seu tipo(Relacional ou não-relacional), até qual softawre de banco de dados será utilizado. Esse problema também implica na abertura do documento de arquitetura. 


Será realizada uma call(a ser marcada após melhor entendimento a respeito das diretrizes do projeto) contando com membros de todas as equipes para finalizar a escolha das tecnologias a serem acertadas, e aberturas a discussões quanto a outras opções para desenvolvimento serão realizadas.

Será verificado o nível de proficiência nas linguagens e frameworks escolhidos com todos os componentes, para entendimento e divisão das equipes de desenvolvimento.

### Em resumo

- [x] Front-End
- [ ] Back-End **em vias de conclusão - a depender das especificações do cliente**
- [ ] Banco de Dados **em vias de conclusão - a depender das especificações do cliente**
- [ ] Documento de Arquitetura **A ser inicializado ao fim da seleção final de tecnologia**

**Comment by SwampTG** [comment]
Para criação de PDFs com JS/Node: [http://pdfmake.org/playground.html](pdfmake) dá para testar!
Para criação de PDFs com Py/Django, com exemplos: [https://www.reportlab.com/documentation/tutorial/#json-to-pdf-invoice-tutorial](ReportLab)

**Comment by SwampTG** [comment]
> Para criação de PDFs com JS/Node: [pdfmake](http://pdfmake.org/playground.html) dá para testar!
> Para criação de PDFs com Py/Django, com exemplos: [ReportLab](https://www.reportlab.com/documentation/tutorial/#json-to-pdf-invoice-tutorial)

**Comment by pedrohelias** [comment]
Finalizada a seleção de tecnologias.
A princípio, até a necessidade de nova demanda de soluções, foi verificada as possibilidades e tomada a decisão juntamente ao desenvolvimento de se utilizar:

React(front-end) + Django API(back-end) + MongoDB(banco)

Acreditamos que tais soluções tecnológicas se adequarão melhor ao nosso projeto e suas necessidades.
