### ISSUE TITLE
Teste do Docker - Geral

### ISSUE THREAD

**Issue by SwampTG** [fga-eps-mds/2021-1-hospitalar#88]
# Descrição:

Realizar testes para verificar se o Docker atende às dependências do projeto, versões de tecnologias e compatibilidade com arquivos necessários para o projeto.

# Pré-requisitos:

- [x] #67

# Tarefas:

- [x]  Reunir-se com DevOps

# Testes
LISTAR OS TESTES NA ISSUE
- [x] Teste de integração
- [x] Teste de Refresh - Ver se as alterações salvas no código são refletidas no container automaticamente.

# Critério de aceitação:

- [x] Docker atende as necessidades  do projeto
- [x] Docker passou nos testes
- [ ] Front-end e back-end rodando pelo Docker

**Comment by castroricardo1** [comment]
Teste de front end com react ja testado e funcionando

**Comment by Eduardo-RFarias** [comment]
Tem que testar se as edições em alguma parte do front reflete no cantainer.

**Comment by SwampTG** [comment]
Talvez não seja um problema. Pelo que eu entendi, o container é para testar e subir a aplicação. Ao desenvolver acho que a gente não usa tanto, só na hora de testar mesmo.

**Comment by castroricardo1** [comment]
Configurei o backend e o banco de dados, se alguém puder testar em outra máquina além da minha

**Comment by Eduardo-RFarias** [comment]
Faz um markdown aí no código ensinando como que roda. Eu posso testar depois.

**Comment by Eduardo-RFarias** [comment]
Deu um erro no meu teste aqui.
Estava seguindo os passos do Markdown presente na pasta docs/produto/Docker.
### Erro que apareceu no terminal:
>![image](https://user-images.githubusercontent.com/52677538/132443648-0043193d-539f-4835-a108-f3961f7f8d11.png)

**Comment by castroricardo1** [comment]
@Eduardo-RFarias ja vi aqui o erro, no Markdown, está build compose up, o correto é build-compose up, testa novamente

**Comment by Eduardo-RFarias** [comment]
Testei o docker aqui e aconteceu o seguinte:
- O Frontend compilou sem problemas.
- O Backend também compilou e a API está online, mas ainda teve um erro que vou descrever a seguir.
- O mongo DB não funcionou o terminal mostrou vários erros relacionados a ele. Agora o docker tenta reiniciar o container do db-mongo-express_1 e o mesmo erro se repete.

>ERRO:
![image](https://user-images.githubusercontent.com/52677538/132551446-7a0e375a-992b-406b-a554-0ebd9c0905d5.png)

**Comment by castroricardo1** [comment]
Aqui está igual, creio que por não ter nada configurado de backend e db (nesta branch), esses erros estão ocorrendo

**Comment by Eduardo-RFarias** [comment]
Vou cadastrar uma tabela com CRUD aqui pra testar.
Mais tarde mostro oq aconteceu.

**Comment by castroricardo1** [comment]
Consegui solucionar o problema com o mongo-express, na porta 8081, ja conseguimos acessar ele

![Sem título](https://user-images.githubusercontent.com/83254747/132607998-a3da8497-5501-4fcf-9fda-b740277fa887.png)

**Comment by Eduardo-RFarias** [comment]
Vi que vcs conseguiram resolver a parte do mongo e tá funcionando mesmo.
Mas ainda está tendo problemas no backend:
- Não consigo fazer requisições pra API pois o backend apresenta essa erro:
>![image.png](https://images.zenhubusercontent.com/60f980d321a8929306b45690/96505834-c730-4fc3-b5a0-ee78975ab417)

**Comment by EduardoGurgel** [comment]
### Teste modelo Banco de dados - Time A

### Images
<img width="542" alt="2b" src="https://user-images.githubusercontent.com/51385738/132959537-be6243df-81b7-42ca-bb37-f7c706cac0ba.PNG">

### Volumes
<img width="540" alt="3" src="https://user-images.githubusercontent.com/51385738/132959540-d90c7430-6bcd-4460-afba-37fcc285cfea.PNG">

### Adicionar Item
<img width="812" alt="1a" src="https://user-images.githubusercontent.com/51385738/132959561-bd6e966a-2756-468c-8d78-e179237690a5.PNG">

### Mongo Compass
<img width="548" alt="2a" src="https://user-images.githubusercontent.com/51385738/132959563-02527149-f179-4064-bac0-66c8f125f96c.PNG">

**Comment by victordscabral** [comment]
Testes realizados, com imagens postadas nos comentários. Issue finalizada.

**Comment by Eduardo-RFarias** [comment]
A issue foi fechada mas o problema não foi resolvido. Solicito que a equipe que fechou explique como os testes foram feitos.
