### ISSUE TITLE
Levantamento de bibliografia do Doc. Arquitetura

### ISSUE THREAD

**Issue by klyssmannoliveira** [fga-eps-mds/2021-1-hospitalar#9]
# Tarefas

- [x] Levamentamento de material bibliográfico para eloboração do documento de Arquitetura.

# Critérios de aceitação
Criar o modelo do documento, deixando pronto para elaboração.

**Comment by EduardoGurgel** [comment]
### Referências da Arquitetura de outros projetos:

- https://github.com/fga-eps-mds/2017.2-QueroCultura/wiki/Arquitetura

- https://github.com/fga-eps-mds/2017.2-Receita-Mais/wiki/Documento-de-Arquitetura

- https://github.com/fga-eps-mds/fisCAE-2017-2/wiki/Documento-de-arquitetura

- https://fga-eps-mds.github.io/2019.2-Amika-Wiki/#/docs/projeto/documentoarquitetura

- https://fga-eps-mds.github.io/2019.1-MaisMonitoria/docs/doc-arquitetura

- https://fga-eps-mds.github.io/2018.1-Dr-Down/mds/ARCHITECTURE_DOCUMENT/#3-requisitos-e-restricoes-arquiteturais

**Comment by EduardoGurgel** [comment]
### Sugestão de modelo
 - Introdução

-  Representação da arquitetura 

 

- Metas e Restrições de Arquitetura

-  Visão de casos de uso

-  Visão lógica

-  Visão de implantação

-  Diagrama de sequência

 

- Diagrama de usuário

-  Visão de implementação

-  Visão de dados

-  Qualidade

-  Requisitos Mínimos dos Sistemas

-  Referências

**Comment by victordscabral** [comment]
Tarefa concluída. Levamentamento de material bibliográfico realizada.
