### ISSUE TITLE
Configurar Ambiente de Desenvolvimento - Time A

### ISSUE THREAD

**Issue by victordscabral** [fga-eps-mds/2021-1-hospitalar#90]
# Descrição:

Essa issue tem como objetivo a configuração do ambiente de desenvolvimento de todos os membros do Time A, de maneira que o desenvolvimento ocorra de forma contínua e padronizada.

# Tarefas:

- [x] Ambiente de desenvolvimento do @EduardoGurgel  configurado
- [x] Ambiente de desenvolvimento do @jvsdurso configurado
- [x] Ambiente de desenvolvimento do @klyssmannoliveira  configurado
- [x] Ambiente de desenvolvimento do @pedrohelias  configurado
- [x] Ambiente de desenvolvimento do @PedroCassianoMartins  configurado
- [x] Ambiente de desenvolvimento do @victordscabral configurado

# Critério de aceitação:

- [x] Ambiente de desenvolvimento de todo o Time A realizado.

**Comment by klyssmannoliveira** [comment]
Meu ambiente está configurado conforme o dojo.

**Comment by victordscabral** [comment]
Meu ambiente está configurado conforme o dojo.

**Comment by EduardoGurgel** [comment]
Ambiente configurado.

**Comment by jvsdurso** [comment]
Ambiente configurado.

**Comment by pedrohelias** [comment]
Ambiente configurado

**Comment by klyssmannoliveira** [comment]
Tarefa concluída, issue fechada!
