### ISSUE TITLE
Revisão dos documentos do projeto - Geral

### ISSUE THREAD

**Issue by victordscabral** [fga-eps-mds/2021-1-hospitalar#92]
# Descrição:

Essa issue tem como objetivo a revisão de todos os documentos do projeto, analisando possíveis revisões e os preparando para a Release 1. Ela é diretamente ligada e complementada pela issue [#91 Análise de documentos do projeto - Geral ](https://github.com/fga-eps-mds/2021-1-hospitalar/issues/91).

# Tarefas:

- [x] Reunião entre POs e Scrum Masters para divisão dos documentos para cada time
- [x] Revisão de todos os documentos do projeto
- [x] Comentários na issue se há necessidade de revisão do documento ou não

# Critério de aceitação:

- [x] Reunião realizada
- [x] Todos os documentos do projeto revisados
- [x] Comentários se há necessidade de revisão do documento ou não

**Comment by klyssmannoliveira** [comment]
O documento de identidade visual precisa ser melhorado.

**Comment by victordscabral** [comment]
Revisão dos documentos do projeto realizada. Não há necessidade de gerar documento. Issue finalizada.
